Do not use fastlane args, but envs only, as args are deliver action specific

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -61,28 +61,60 @@ workflows:
     - SAMPLE_APP_URL: "https://github.com/bitrise-samples/sample-apps-fastlane-test.git"
     - BITRISE_PROJECT_PATH: ./sample-apps-fastlane-test.xcodeproj
     - BITRISE_SCHEME: sample-apps-fastlane-test
+    - INFO_PLIST_PATH: ./sample-apps-fastlane-test/Info.plist
     steps:
+    - script:
+        title: Clean saved Fastlane session cookie
+        inputs:
+        - content: rm -rf ~/.fastlane
     - script:
         inputs:
         - content: rm -rf ./_tmp
     - change-workdir:
         title: Switch working dir to test/_tmp dir
-        run_if: true
+        run_if: "true"
         inputs:
         - path: ./_tmp
         - is_create_path: true
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone:
+        inputs:
+        - repository_url: $SAMPLE_APP_URL
+        - branch: signing-update
+        - clone_into_dir: "."
+    - ios-auto-provision-appstoreconnect:
+        inputs:
+        - distribution_type: app-store
     - script:
         inputs:
-        - content: git clone $SAMPLE_APP_URL .
-    - ios-auto-provision@1.3.1:
+        - content: |-
+            #!/usr/bin/env bash
+            CURRENT_BUILD_NUMBER=${BITRISE_BUILD_NUMBER}
+            BITRISE_BUILD_NUMBER=$((($(gdate +%Y%m%d%H%M%S)-20000000000000)*10000))
+            if [[ -z "${BITRISE_BUILD_NUMBER}" ]]; then
+              echo "error: failed to calculated build number"
+              exit 1
+            fi
+            if [[ -n "${CURRENT_BUILD_NUMBER}" ]]; then
+              BITRISE_BUILD_NUMBER=$((${BITRISE_BUILD_NUMBER}+${CURRENT_BUILD_NUMBER}))
+            fi
+
+            envman add --key BITRISE_BUILD_NUMBER --value "${BITRISE_BUILD_NUMBER}"
+    - set-xcode-build-number:
+        title: Set Build Number
+        run_if: "true"
         inputs:
-        - generate_profiles: 'yes'
-        - distribution_type: app-store
+        - build_version: $BITRISE_BUILD_NUMBER
+        - plist_path: $INFO_PLIST_PATH
+        - build_version_offset: $BITRISE_BUILD_VERSION_OFFSET
     - path::./:
         inputs:
         - lane: release
         - work_dir: ./
         - verbose_log: "yes"
+        - connection: $AUTH_CONNECTION
+        - api_key_path: $AUTH_API_KEY_PATH
+        - api_issuer: $AUTH_API_ISSUER
+        - app_password: $AUTH_APP_PASSWORD
 
   # ----------------------------------------------------------------
   # --- Utility workflows
