Fix issue with version numbers not incrementing properly when multiple uploads are made to appstore connect in the same workflow

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -181,13 +181,14 @@ workflows:
         - content: |-
             #!/usr/bin/env bash
             CURRENT_BUILD_NUMBER=${BITRISE_BUILD_NUMBER}
-            BITRISE_BUILD_NUMBER=$((($(gdate +%Y%m%d%H%M%S)-20000000000000)*10000))
-            if [[ -z "${BITRISE_BUILD_NUMBER}" ]]; then
-              echo "error: failed to calculated build number"
-              exit 1
-            fi
             if [[ -n "${CURRENT_BUILD_NUMBER}" ]]; then
-              BITRISE_BUILD_NUMBER=$((${BITRISE_BUILD_NUMBER}+${CURRENT_BUILD_NUMBER}))
+              BITRISE_BUILD_NUMBER=$((${CURRENT_BUILD_NUMBER}+1))
+            else
+              BITRISE_BUILD_NUMBER=$((($(gdate +%Y%m%d%H%M%S)-20000000000000)*10000))
+              if [[ -z "${BITRISE_BUILD_NUMBER}" ]]; then
+                echo "error: failed to calculate build number"
+                exit 1
+              fi
             fi
 
             envman add --key BITRISE_BUILD_NUMBER --value "${BITRISE_BUILD_NUMBER}"
@@ -198,7 +199,7 @@ workflows:
         - build_version: $BITRISE_BUILD_NUMBER
         - plist_path: $INFO_PLIST_PATH
         - build_version_offset: $BITRISE_BUILD_VERSION_OFFSET
-        - build_short_version_string: "1.0.1"
+        - build_short_version_string: "1.0.2"
 
 
   audit-this-step:
